version: '3'

services:
  db:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: exerciseBdd
      MYSQL_ROOT_PASSWORD: cyrilledb
      MYSQL_USER: root
      MYSQL_PASSWORD: cyrilledb

    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: cyrilledb
    ports:
      - '8080:80'

volumes:
  db_data:
